### ISSUE TITLE
Upgrade to api v3

### ISSUE THREAD

**Issue by osos** [pakkelabels/php#10]
Please upgrade your sdk to facilitate the new api v3: https://app.pakkelabels.dk/api/public/v3/specification

among others this facilitates shipment_monitor, which I am looking forward to using.

I have tried updating, but cannot get curl basic auth to work with api v3.

**Comment by Hungor** [comment]
Hi @osos 

It is on our to-do. We expect this to be addressed in a couple of weeks. 

Regarding your questions with curl basic auth, you can use the API credentials from your account, it is no longer needed to request an access token everytime.
Example:
```
$ch = curl_init();
$username = "d8fb61fe-0a4f-4e11-81f8-6efd3513bd43"
$password = "976ff6f2-3528-4f4f-9e7d-007e9a074037"
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'Content-Type: application/json',
  )
);
curl_setopt($ch, CURLOPT_USERPWD, $username . ":" . $password);

```

**Comment by SolidGeek** [comment]
Looking forward to see the new sdk for v3, how long can we expect to wait?

**Comment by Hungor** [comment]
It is now supported. #11
