### ISSUE TITLE
Issues with Xampp (latest version)

### ISSUE THREAD

**Issue by boutzamat** [pakkelabels/php#3]
Hello there.

Does this library require any special PHP extensions?
I made a example with the provided code in your Readme page, and it doesnt work on Localhost.

```
try {
   $label = new Pakkelabels('**********', '**********');
   $pdk_stores = $label->pdk_droppoints(array(
      'zipcode' => '5240',
      'street' => 'Strandvejen'
   ));
   echo $pdk_stores;
}

catch(PakkelabelsException $e) {
   echo $e->getMessage();
   echo 'something is wrong...';
}
```

_NOTE: This is a simplyfied example, a lot has been trimmed_

The getMessage is not returning anything, but i get the message "Something is wrong" meaning that the "try" failed.

The very same code works perfect on a webserver, but my project is developed using GitHub, so i prefer having the library work on localhost.

This is the error message i get:

> Fatal error: Uncaught exception 'PakkelabelsException' in C:\xampp\htdocs\pakkelabels\Pakkelabels.php:120 Stack trace: 
> # 0 C:\xampp\htdocs\pakkelabels\Pakkelabels.php(18): Pakkelabels->_make_api_call('users/login', true, Array)
> # 1 C:\xampp\htdocs\pakkelabels\Pakkelabels.php(14): Pakkelabels->login()
> # 2 C:\xampp\htdocs\pakkelabels\index.php(7): Pakkelabels->__construct('MIN BRUGER', 'MIN NØGLE')
> # 3 {main} thrown in C:\xampp\htdocs\pakkelabels\Pakkelabels.php on line 120

For security reasons, i have ofcourse removed the API user and key.

**Comment by boutzamat** [comment]
SOAP is the answer. This library depends on SOAP client.
Thank you for the answer.

**Comment by JanC89** [comment]
This library doesn't depend on SOAP. 

The API from Pakkelabels.dk is a RESTful one. The only plugin needed for your PHP installation is [CURL](http://php.net/manual/en/book.curl.php)

**Comment by boutzamat** [comment]
Hmm, im pretty sure CURL was enabled at the time of the issue. Installing SOAP fixed the problem, thats why i was sure it was SOAP dependent. Also, a similar PHP Library from another author was requiring SOAP, thats why i thought SOAP was the solution. Never the less, it works now :)

Thank you for your reply
