### ISSUE TITLE
Issues with createShipment($data) example

### ISSUE THREAD

**Issue by baf-baf** [pakkelabels/php#4]
Hi ! Can you please replace this row

> $shipment = $label->createShipment($data); 

by  this : 

> $shipment = $label->create_shipment($data);

inside  README.md .
The method createShipment() does not exist.

---

Also, the following example is not valid by itself. 
The input array requires additional fields like 'receiver_mobile' and 'receiver_email'. Otherwise,  it will throw PakkelabelsException.

> $data = array(
> 
>   'shipping_agent' => 'pdk',
>       'weight' => '1000',
>       'receiver_name' => 'John Doe',
>       'receiver_address1' => 'Some Street 42',
>       'receiver_zipcode' => '5230',
>       'receiver_city' => 'Odense M',
>       'receiver_country' => 'DK',
>       'sender_name' => 'John Wayne',
>       'sender_address1' => 'The Batcave 1',
>       'sender_zipcode' => '5000',
>       'sender_city' => 'Odense C',
>       'sender_country' => 'DK',
>       'shipping_product_id' => '51',
>       'services' => '11,12',
>       'test' => 'true' // Change to false when going live
>     );
> 
>    $shipment = $label->createShipment($data);
>   echo 'Track&Trace: ' . $shipment['pkg_no'];

Best regards : )

**Comment by Hungor** [comment]
Hi Vitalii,

Thank you. I have updated the documentation now.
Have a great day!

Best,
Hung from Pakkelabels

**Comment by baf-baf** [comment]
Thank you for quick response.
Good luck !
