### ISSUE TITLE
Getting No Shipping Product with ID 517 error when using test data for CreateShipment

### ISSUE THREAD

**Issue by z3r0cfm** [pakkelabels/php#5]
I'm evaluating the api and I am getting the "No Shipping Product with ID 517"
when running the CreateShipment call.

Login works.

Is there anything that needs to be setup aside from the API Keys?

**Comment by Hungor** [comment]
Hi,

You have used a shipping product that is not existing.

Can you try to fetch the freight rates and from that call you can see which shipping products are available?

/Hung
